title: Xan0er's Bl0g
author: Xan0er
email: xan0er@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to a world of CTF Learnings! Here you will find the
  writeups written by me on various CTF topics such as Web Exploitation, 
  Forensics, Reversing, OSINT and much more...🐱‍💻
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/page/:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
future: true

url: https://xan0er.tech

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: xan0er-tech.disqus.com

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/xan0er
      icon: fab fa-twitter-square
      color: cyan
    - url: https://github.com/xan0er
      icon: fab fa-github-square
      color: red
    - url: https://discordapp.com/users/Xan0er#3102
      icon: fab fa-discord
      color: purple
    - url: https://www.linkedin.com/in/gurvinder-singh-360691123/
      icon: fab fa-linkedin
      color: blue
    - url: /feed.xml
      icon: fas fa-rss-square
      color: teal

  info_links:
    - url: /badges
      icon: fas fa-trophy
      color: blue
    - url: /about
      icon: fas fa-address-card
      color: green
    - url: /tags
      icon: fas fa-tags
      color: pink
    - url: /search
      icon: fas fa-search
      color: yellow

  show_author: true

  animation_speed: 50

# Build settings
remote_theme: bitbrain/jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: xan0er

upcase_list:
  - ctf